# Generated by Django 5.2.1 on 2025-05-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area_sqft', models.IntegerField(verbose_name='Area (sqft)')),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('features', models.TextField(blank=True, help_text='Comma-separated values, e.g., Garden, Pool')),
                ('status', models.CharField(choices=[('FOR_SALE', 'For Sale'), ('SOLD', 'Sold'), ('PENDING', 'Pending'), ('DRAFT', 'Draft')], default='DRAFT', max_length=10)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-date_added'],
            },
        ),
    ]
